[package]
authors = ["happyboy"]
description = "lightweight web framework"
edition = "2021"
name = "bubble"
version = "0.1.0"
[dependencies]
bubble-config = {version = "0.1.0", path = "../bubble-config"}
bubble-controller = {version = "0.1.0", path = "../bubble-controller"}
